In [11]:
import numpy as np
import numpy.random as rd

In [10]:
print(np.zeros(10))
print(np.ones(20))
print(np.arange(20, 41))
print(np.zeros((3,3)))
print(np.arange(1, 10).reshape(3,3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(rd.randn(3, 3))
print(rd.standard_normal((3, 3)))

[[-0.49392465  0.38317298 -0.51902875]
 [ 2.78345598 -1.18049056  0.06098588]
 [-0.1659271  -0.99839011 -0.61908663]]
[[ 0.79161692 -0.64780561  1.27020133]
 [ 0.67370087  1.14276958  0.69687868]
 [-0.76941632  0.15862532  1.73482159]]


In [30]:
print(np.identity(3))
print(np.eye(3, k=0))
print(np.eye(3, k=1))
print(np.eye(3, k=-1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [31]:
n1 = np.array([
    [3, 4],
    [2, 3]
], dtype=np.int16)
n2 = np.array([
    [5, 3],
    [1, 4]
], dtype=np.int16)

print(n1)
print(n2)

[[3 4]
 [2 3]]
[[5 3]
 [1 4]]


In [36]:
print(n1 + n2)
print(n1 - n2)
print(n1 * n2) # this is not matrix multiplication
print(n1.dot(n2)) # this is matrix multiplication

[[8 7]
 [3 7]]
[[-2  1]
 [ 1 -1]]
[[15 12]
 [ 2 12]]
[[19 25]
 [13 18]]
