In [25]:
import numpy as np

In [26]:
marks = [
    [5, 6, 10],
    [10, 4, 2],
    [7, 10, 1]
]

In [27]:
n1 = np.array(marks, dtype=np.int16)
print(type(n1))
print(n1)
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

<class 'numpy.ndarray'>
[[ 5  6 10]
 [10  4  2]
 [ 7 10  1]]
2
(3, 3)
int16


In [28]:
# indexing
c1 = n1[0]
print(c1)
print(type(c1))
print(n1[-1])
print(n1[1][-1]) # traditional python indexing is not optimal
print(n1[1,-1]) # this is more optimal than the above
print(n1[[0, -1]]) # multiple indexing

[ 5  6 10]
<class 'numpy.ndarray'>
[ 7 10  1]
2
2
[[ 5  6 10]
 [ 7 10  1]]


In [29]:
# slicing
print(n1)
print(n1[[0,1]])
print(n1[:2]) # slicing to achive what indexing was doing above
print(n1[-2:]) # last 2 divisions in the class std
print(n1[:2, -2:]) # slice along the rows and then across the columns
print(n1[-2:, :2])

[[ 5  6 10]
 [10  4  2]
 [ 7 10  1]]
[[ 5  6 10]
 [10  4  2]]
[[ 5  6 10]
 [10  4  2]]
[[10  4  2]
 [ 7 10  1]]
[[ 6 10]
 [ 4  2]]
[[10  4]
 [ 7 10]]


In [30]:
# slicing + indexing
print(n1)
print(n1[:2, [0, -1]])
print(n1[[0, -1], -2:])

[[ 5  6 10]
 [10  4  2]
 [ 7 10  1]]
[[ 5 10]
 [10  2]]
[[ 6 10]
 [10  1]]


In [31]:
print(n1)
n2 = n1.copy()
# deduct marks by 1 for students from first and last division
n2[[0, -1]] -= 1
print(n2)

[[ 5  6 10]
 [10  4  2]
 [ 7 10  1]]
[[ 4  5  9]
 [10  4  2]
 [ 6  9  0]]


In [33]:
print(n1)
n3 = n1.copy()
n3 -= [
    [1],
    [2],
    [1]
]
print(n3)

[[ 5  6 10]
 [10  4  2]
 [ 7 10  1]]
[[4 5 9]
 [8 2 0]
 [6 9 0]]


In [35]:
print(n1)
n4 = n1.copy()
n4 -= [1, 0, 1]
print(n4)

[[ 5  6 10]
 [10  4  2]
 [ 7 10  1]]
[[ 4  6  9]
 [ 9  4  1]
 [ 6 10  0]]


In [37]:
print(n1)
n10 = np.where(n1 > 6, 1, 0)
print(n10)

[[ 5  6 10]
 [10  4  2]
 [ 7 10  1]]
[[0 0 1]
 [1 0 0]
 [1 1 0]]
