In [1]:
import numpy as np

In [2]:
marks = [
    [5, 6, 10],
    [10, 4, 2],
    [7, 10, 1]
]

In [3]:
n1 = np.array(marks, dtype=np.int16)
print(type(n1))
print(n1)
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

<class 'numpy.ndarray'>
[[ 5  6 10]
 [10  4  2]
 [ 7 10  1]]
2
(3, 3)
int16
