In [1]:
import numpy as np

In [2]:
pointers = [5, 6, 10, 10, 1, 4, 3, 7, 9, 10, 1]

In [7]:
# numpy array
n1 = np.array(pointers, dtype=np.int16)
print(type(n1))
print(n1)
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

<class 'numpy.ndarray'>
[ 5  6 10 10  1  4  3  7  9 10  1]
1
(11,)
int16


In [10]:
# a new list of pointers deducted by 1
n2 = n1 - 1
print(n2)
print(type(n2))
# Vectorized operations
# All arithmetic operators on numpy array object are vectorized

[4 5 9 9 0 3 2 6 8 9 0]
<class 'numpy.ndarray'>


In [16]:
# indexing
print(n1[0])
print(n1[1])
print(n1[-1])
print(n1[-2])

# multiple indexing
print(n1[[0, -2]])

5
6
1
10
[ 5 10]


In [21]:
# slicing
print(n1)
print(n1[:3])
print(n1[-4:])

[ 5  6 10 10  1  4  3  7  9 10  1]
[ 5  6 10]
[ 7  9 10  1]


In [18]:
# a new list of people who have scrore more than 5 pointer
n3 = n1 > 5
print(n3)
print(type(n3))
# Relational operators on numpy array are vectorized

n4 = n1[n1 > 5]
print(n4)

n5 = n1[n1 == 10]
print(n5)

[False  True  True  True False False False  True  True  True False]
<class 'numpy.ndarray'>
[ 6 10 10  7  9 10]
[10 10 10]


In [23]:
# Mathematical functions
print(n1)
print(n1.min())
print(n1.max())
print(n1.mean())
print(n1.cumsum())
print(n1.std())
print(n1.var())

[ 5  6 10 10  1  4  3  7  9 10  1]
1
10
6.0
[ 5 11 21 31 32 36 39 46 55 65 66]
3.330301651638946
11.090909090909092


In [26]:
print(n1)
print(n1.sort())
print(n1)

[ 1  1  3  4  5  6  7  9 10 10 10]
None
[ 1  1  3  4  5  6  7  9 10 10 10]


In [31]:
n20 = np.array(pointers, dtype=np.int16)
print(n20)
n20[-1] = 2
print(n20)
n20[[0, -2]] = [7, 9]
print(n20)

n20[:3] = 0 # broadcasting
print(n20)

[ 5  6 10 10  1  4  3  7  9 10  1]
[ 5  6 10 10  1  4  3  7  9 10  2]
[ 7  6 10 10  1  4  3  7  9  9  2]
[ 0  0  0 10  1  4  3  7  9  9  2]
